### ISSUE TITLE
Attribute all authors of a merge

### ISSUE THREAD

**Issue by sunesimonsen** [sunesimonsen/offline-github-changelog#1]
Find all of the commits of a merge and attribute the set of authors for the PR's.

**Comment by papandreou** [comment]
Maybe you could use `git log --format=... $(git merge-base master <commit>)..<commit>` where `<commit>` is the last commit on the branch, ie. the second parent of the merge commit?

**Comment by sunesimonsen** [comment]
@papandreou thanks for the suggestion, it seems reasonable. I'll look into this when I have a bit of time.

**Comment by sunesimonsen** [comment]
Fixed by https://github.com/sunesimonsen/offline-github-changelog/pull/2
